### PR TITLE
Make biplot an s3 method for the stats function

### PR DESCRIPTION
**Pull request by Alanocallaghan**
`pcaTools::biplot` masks `stats::biplot` in a semi-nasty way imo. after loading pcatools you get some odd unintuitive error message* if you try to biplot a stats PCA object. It'd be a lot more seamless if the function in this package just extended what the stats function does instead of clobbering it. I see two ways of doing this - one is what I've done. The second is to define a new s3 generic that dispatches to `pca` objects like this, and in the default case calls `stats::biplot`.

*Something like `Error in round(pcaobj$variance[x], digits = 2): non-numeric argument to mathematical function`

### CODE REVIEW

**Comment by LTLA** [comment]
Chipping in as requested: makes sense to me. I can't remember all of the S3 export rules, but this looks reasonable.

**Comment by kevinblighe** [comment]
Thanks @Alanocallaghan @LTLA , I will sort this out at the weekend

**Comment by kevinblighe** [comment]
Hey @Alanocallaghan @LTLA , I am currently getting this warning from R CMD CHECK:

```
* checking S3 generic/method consistency ... WARNING
biplot:
  function(x, ...)
biplot.pca:
  function(pcaobj, x, y, showLoadings, ntopLoadings, showLoadingsNames,
           colLoadingsNames, sizeLoadingsNames, boxedLoadingsNames,
           fillBoxedLoadings, drawConnectorsLoadings,
           widthConnectorsLoadings, colConnectorsLoadings,
           lengthLoadingsArrowsFactor, colLoadingsArrows,
           widthLoadingsArrows, alphaLoadingsArrow, colby, colkey,
           colLegendTitle, singlecol, shape, shapekey,
           shapeLegendTitle, pointSize, legendPosition, legendLabSize,
           legendTitleSize, legendIconSize, encircle, encircleFill,
           encircleFillKey, encircleAlpha, encircleLineSize,
           encircleLineCol, ellipse, ellipseType, ellipseLevel,
           ellipseSegments, ellipseFill, ellipseFillKey, ellipseAlpha,
           ellipseLineSize, ellipseLineCol, xlim, ylim, lab, labSize,
           boxedLabels, selectLab, drawConnectors, widthConnectors,
           colConnectors, maxoverlapsConnectors, directionConnectors,
           xlab, xlabAngle, xlabhjust, xlabvjust, ylab, ylabAngle,
           ylabhjust, ylabvjust, axisLabSize, title, subtitle, caption,
           titleLabSize, subtitleLabSize, captionLabSize, hline,
           hlineType, hlineCol, hlineWidth, vline, vlineType, vlineCol,
           vlineWidth, gridlines.major, gridlines.minor, borderWidth,
           borderColour, returnPlot)

See section ‘Generic functions and methods’ in the ‘Writing R
Extensions’ manual.
```
Any ideas?

----------------------
----------

Also, it now doesn't seem to like this code chunk in the vignette:  https://github.com/kevinblighe/PCAtools/blob/master/vignettes/PCAtools.Rmd#L530-L545

```
Quitting from lines 531-545 (PCAtools.Rmd) 
Error: processing vignette 'PCAtools.Rmd' failed with diagnostics:
argumento de comprimento zero
--- failed re-building ‘PCAtools.Rmd’
```

Currently trying to debug these

**Comment by Alanocallaghan** [comment]
Ah of course, sorry.

I think this:
>`* checking S3 generic/method consistency ... WARNING`
Is asking that both arg lists should start with x, not `x` for the generic and `pcaobj` for the method.

Checking the vignette now

**Comment by kevinblighe** [comment]
Hey Alan, no problem, I'll be adding you to contributors anyway. As I understand, it should now automatically be able to distinguish between stats::biplot and PCAtools::biplot, right? I'm not sure that it's doing that but I need to test it more. Is the NAMESPACE an issue because I automatically generate it with roxygen. My local NAMESPACE is:
```
# Generated by roxygen2: do not edit by hand

S3method(biplot,pca)
export(chooseGavishDonoho)
export(chooseMarchenkoPastur)
export(eigencorplot)
export(findElbowPoint)
export(getComponents)
export(getLoadings)
export(getVars)
export(pairsplot)
export(parallelPCA)
export(pca)
export(plotloadings)
export(screeplot)
import(BiocParallel)
import(Matrix)
import(cowplot)
import(ggplot2)
import(ggrepel)
importFrom(BiocParallel,SerialParam)
importFrom(BiocParallel,bpmapply)
importFrom(BiocSingular,ExactParam)
importFrom(BiocSingular,runPCA)
importFrom(DelayedArray,DelayedArray)
importFrom(DelayedMatrixStats,colVars)
importFrom(Rcpp,sourceCpp)
importFrom(dqrng,generateSeedVectors)
importFrom(grDevices,colorRampPalette)
importFrom(lattice,levelplot)
importFrom(lattice,ltext)
importFrom(lattice,panel.levelplot)
importFrom(methods,is)
importFrom(reshape2,melt)
importFrom(stats,biplot)
importFrom(stats,cor)
importFrom(stats,cor.test)
importFrom(stats,p.adjust)
importFrom(stats,symnum)
importFrom(stats,var)
useDynLib(PCAtools)
```

**Comment by Alanocallaghan** [comment]
The idea is people will always call `stats::biplot`, and when PCAtools is loaded it'll attach another method to that generic.

I think to get rid of the check warnings (and the error) you need to rename the `x` and `y` arguments and add a `...` argument. I've got a PR ready but need to test it further

**Pull request merged**
