### PR TITLE
Added Horn's parallel analysis

### PR DESCRIPTION
**Pull request by LTLA**
I'll apologize in advance because there's a lot more going on here than I had first anticipated when I proposed to put this method in. This is because it's (i) in C++, (ii) parallelized for speed and (iii) involves randomization. Getting these three things right at the same time involves a bit of work:

- _Rcpp_ to perform the shuffling of observations quickly in C++. 
- _beachmat_ to shuffle any matrix representation, not just ordinary dense matrices.
- _BiocParallel_ to parallelize the iterations of Horn's parallel analysis.
- _dqrng_ to provide a safely parallelizable random number generator.
- _BH_ to provide a random shuffling method that is not compiler-dependent.

Do you have any familiarity with compiling packages from source? If not: it is plug-and play on Unix, mostly easy on Mac (I vaguely remember installing gcc via homebrew; I think it just worked), and more painful on Windows. Note that this is only relevant to developers, as BioC will compile it for end-users.

### CODE REVIEW

**Comment by kevinblighe** [comment]
Hey Aaron, thanks very much for all of this - this will have significantly strengthened the package. Yes, I have experience compiling packages from source. I will take a look at everything at next opportunity. You've tested it at your end?

**Comment by kevinblighe** [comment]
Thanks Aaron! I have tested Horn's function and it works fine. I will be updating the docs over the next week or so.

**Comment by LTLA** [comment]
I also have a bunch of unit tests that I could migrate over from _scran_, but I didn't know where to put them. It looks like the `inst/unitTests` directory uses _testthat_, but I didn't see any _testthat_ dependency. I wonder whether it would be easier to put the tests in `tests/testthat` directly?

**Comment by kevinblighe** [comment]
Sure, feel free to make additions. I am not too experienced with the test functionality that Bioconductor now requires.

**Pull request merged**
